version: "3"


services:
  express-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGODB_DB_NAME=test
      - MONGODB_USER=root
      - MONGODB_PASSWORD=myadmin2007
      - MONGODB_IP=mongo
      - MONGODB_PORT=27017
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongo
  

  mongo :
    image: mongo:4.0.28-xenial
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myadmin2007
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


volumes:
  mongo_data: